# 12-flask-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secret
  namespace: python-app
type: Opaque
data:
  # Flask's SECRET_KEY for session management (base64 encoded)
  # Replace with a strong, randomly generated key for production:
  # echo -n 'your_very_long_and_random_flask_secret_key_here' | base64
  flask-secret-key: Y2hhbmdlX21lX2luX3Byb2R1Y3Rpb24= # base64 encoded "change_me_in_production"
  
  # MySQL credentials for the Flask application to connect to the database
  # These are base64 encoded versions of "root" and "admin"
  mysql-user: cm9vdA==   # base64 encoded "root"
  mysql-password: YWRtaW4= # base64 encoded "admin" (from 4-mysql-secret.yaml)

