apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: python-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/mysql-storage/mysql-pv-loginapp
    server: 10.0.0.100
