apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: python-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS login_db;
    USE login_db;
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      firstname VARCHAR(50) NOT NULL,
      username VARCHAR(100) NOT NULL UNIQUE,
      email VARCHAR(100) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL -- <-- FIX: Changed from VARCHAR(150) to VARCHAR(255)
    );
