apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
  namespace: python-app
data:
  PMA_HOST: mysql   # Name of the MySQL service
  PMA_PORT: "3306"
  PMA_USER: root    # MySQL username
  PMA_PASSWORD: admin  # MySQL password
