# deployment-phpmyadmin.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: registry.kube.lan/phpmyadmin:5.2.2
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: phpmyadmin-config
